# Generated by Django 5.2.13 on 2026-05-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactName', models.CharField(default='', max_length=30)),
                ('EmailId', models.CharField(default='', max_length=30)),
                ('PhoneNum', models.CharField(default='', max_length=30)),
                ('Subject', models.CharField(default='', max_length=50)),
                ('Message', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=30)),
                ('LastName', models.CharField(default='', max_length=30)),
                ('UserName', models.CharField(default='', max_length=30)),
                ('Password', models.CharField(default='', max_length=30)),
                ('EmailId', models.CharField(default='', max_length=30)),
                ('PhoneNum', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=30)),
                ('Image', models.CharField(default='', max_length=30)),
                ('StaffType', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=30)),
                ('LastName', models.CharField(default='', max_length=30)),
                ('UserName', models.CharField(default='', max_length=30)),
                ('Password', models.CharField(default='', max_length=30)),
                ('EmailId', models.CharField(default='', max_length=30)),
                ('PhoneNum', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=30)),
                ('Image', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
