# Generated by Django 5.2.13 on 2026-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstudent',
            old_name='Image',
            new_name='Chapter1',
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter10',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter6',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter7',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter8',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='Chapter9',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='TextResult',
            field=models.CharField(default='', max_length=30),
        ),
    ]
