# Generated by Django 5.2.13 on 2026-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_image_newstudent_chapter1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='Image',
            field=models.CharField(default='', max_length=30),
        ),
    ]
