# Generated by Django 5.2.13 on 2026-05-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_newstudent_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstudent',
            old_name='TextResult',
            new_name='TestResult',
        ),
    ]
