# Generated by Django 5.2.13 on 2026-05-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_textresult_newstudent_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.IntegerField(default=0)),
                ('StudentName', models.CharField(default='', max_length=30)),
                ('Question1', models.CharField(default='', max_length=50)),
                ('Question2', models.CharField(default='', max_length=50)),
                ('Question3', models.CharField(default='', max_length=50)),
                ('Question4', models.CharField(default='', max_length=50)),
                ('Question5', models.CharField(default='', max_length=50)),
                ('Answer1', models.CharField(default='', max_length=50)),
                ('Answer2', models.CharField(default='', max_length=50)),
                ('Answer3', models.CharField(default='', max_length=50)),
                ('Answer4', models.CharField(default='', max_length=50)),
                ('Answer5', models.CharField(default='', max_length=50)),
                ('Result', models.CharField(default='', max_length=50)),
                ('Message', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
