# Generated by Django 5.2.13 on 2026-05-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_newtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtest',
            name='Answer1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='Answer2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='Answer3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='Answer4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='Answer5',
            field=models.IntegerField(default=0),
        ),
    ]
