# Generated by Django 5.2.13 on 2026-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_newtest_answer1_alter_newtest_answer2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter1',
            new_name='JavaChapter1',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter10',
            new_name='JavaChapter10',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter2',
            new_name='JavaChapter2',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter3',
            new_name='JavaChapter3',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter4',
            new_name='JavaChapter4',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter5',
            new_name='JavaChapter5',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter6',
            new_name='JavaChapter6',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter7',
            new_name='JavaChapter7',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter8',
            new_name='JavaChapter8',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='Chapter9',
            new_name='JavaChapter9',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='TestResult',
            new_name='PythonChapter1',
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter10',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter6',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter7',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter8',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='PythonChapter9',
            field=models.CharField(default='', max_length=30),
        ),
    ]
