from django.db import models

# Create your models here.
class NewStudent(models.Model):
    FirstName=models.CharField(max_length=30, default='')
    LastName = models.CharField(max_length=30, default='')
    UserName = models.CharField(max_length=30, default='')
    Password = models.CharField(max_length=30, default='')
    EmailId = models.CharField(max_length=30, default='')
    PhoneNum = models.CharField(max_length=30, default='')
    Address = models.CharField(max_length=30, default='')
    Image = models.CharField(max_length=30, default='')
    JavaChapter1 = models.CharField(max_length=30, default='')
    JavaChapter2 = models.CharField(max_length=30, default='')
    JavaChapter3 = models.CharField(max_length=30, default='')
    JavaChapter4 = models.CharField(max_length=30, default='')
    JavaChapter5 = models.CharField(max_length=30, default='')
    JavaChapter6 = models.CharField(max_length=30, default='')
    JavaChapter7 = models.CharField(max_length=30, default='')
    JavaChapter8 = models.CharField(max_length=30, default='')
    JavaChapter9 = models.CharField(max_length=30, default='')
    JavaChapter10 = models.CharField(max_length=30, default='')
    PythonChapter1 = models.CharField(max_length=30, default='')
    PythonChapter2 = models.CharField(max_length=30, default='')
    PythonChapter3 = models.CharField(max_length=30, default='')
    PythonChapter4 = models.CharField(max_length=30, default='')
    PythonChapter5 = models.CharField(max_length=30, default='')
    PythonChapter6 = models.CharField(max_length=30, default='')
    PythonChapter7 = models.CharField(max_length=30, default='')
    PythonChapter8 = models.CharField(max_length=30, default='')
    PythonChapter9 = models.CharField(max_length=30, default='')
    PythonChapter10 = models.CharField(max_length=30, default='')    
    #TestResult = models.CharField(max_length=30, default='')

class NewStaff(models.Model):
    FirstName=models.CharField(max_length=30, default='')
    LastName = models.CharField(max_length=30, default='')
    UserName = models.CharField(max_length=30, default='')
    Password = models.CharField(max_length=30, default='')
    EmailId = models.CharField(max_length=30, default='')
    PhoneNum = models.CharField(max_length=30, default='')
    Address = models.CharField(max_length=30, default='')
    Image = models.CharField(max_length=30, default='')
    StaffType = models.CharField(max_length=30, default='')

class Contact(models.Model):
    ContactName=models.CharField(max_length=30, default='')
    EmailId = models.CharField(max_length=30, default='')
    PhoneNum = models.CharField(max_length=30, default='')
    Subject = models.CharField(max_length=50, default='')
    Message = models.CharField(max_length=50, default='')
    
class NewTest(models.Model):
    StudentId=models.IntegerField(default=0)
    StudentName=models.CharField(max_length=30, default='')
    Question1 = models.CharField(max_length=50, default='')
    Question2 = models.CharField(max_length=50, default='')
    Question3 = models.CharField(max_length=50, default='')
    Question4 = models.CharField(max_length=50, default='')
    Question5 = models.CharField(max_length=50, default='')
    Answer1 = models.IntegerField(default=0)
    Answer2 = models.IntegerField(default=0)
    Answer3 = models.IntegerField(default=0)
    Answer4 = models.IntegerField(default=0)
    Answer5 = models.IntegerField(default=0)
    Result = models.CharField(max_length=50, default='')
    Message = models.CharField(max_length=50, default='')    